### PR TITLE
Make Tagbar works under iVim (iOS/iPadOS App)

### PR DESCRIPTION
**Pull request by suliveevil**
iVim has a internal command `ictags `  instead of external command `ctags `  .

### CODE REVIEW

**Comment by suliveevil** [comment]
It works

**Comment by alerque** [comment]
Thanks for taking the time to track this down and contribute it. We will be able to get this merged eventually. Unfortunately it is going to clash pretty badly with the Windows fix we have coming in #611. Once that is merged we will need to refactor this a little bit to extend the system command runner function to handle this case as well.

**Comment by suliveevil** [comment]
Sorry for the conflict, I will close the PR.
iVim’s author has replied me that he will try to make the implemented Internal Exuberant CTags Command works like a External Command.

**Comment by alerque** [comment]
You don't need to close the PR, we can work with it and resolve the conflicts. That's not your fault, we just had two fixes needing similar solutions and we need to merge them.

If it looks like we need still need to adapt to work with iVim please open this back up and we'll figure out the details.

**Comment by suliveevil** [comment]
Thank you very much.
I will try to use Tagbar with iVim without changing Tagbar’s code.
Newbie to vimscript, I have lots of tings to learn.

**Comment by alerque** [comment]
Also while you are poking the iVim end of things you might mention to them that Exuberant `ctags` is absurdly old, deprecated, and on the verge of being totally unsupported. Switching to Universal `ctags` would be a very good step as long as it is being messed with!

**Comment by suliveevil** [comment]
I will report your suggestion to iVim🥰🥰🥰

**Pull request closed without merging**
