### PR TITLE
Separate tagbar per tab

### PR DESCRIPTION
**Pull request by jpmv27**
Hi,

Not sure whether you'll be interested in this. In my workflow, it's handy to be able to have a different tagbar on different tabs, so I created these commits.

MV

### CODE REVIEW

**Comment by majutsushi** [comment]
I'm definitely interested in supporting multiple tabs, I work that way too occasionally. I has worked fine for me in the past though, so I'm curious what issue you were having that require the changes you made. Could you give a quick example of wasn't working for you before? I'm just trying to understand the problem better. Thanks!

**Comment by jpmv27** [comment]
Very interesting.

I recall I was running into some issues (I forget the details now,) but
trying it again briefly now with 'stock' tagbar I do not see any issues.

Perhaps they were resolved by some other fixes.

Let's keep the PR on hold while I look into it more carefully.

Regards,
MV

**Comment by jpmv27** [comment]
Well, that's embarassing :-)

Either there was some other plug-in interfering, or I was chasing ghosts, because I don't see any issue with using tagbar simultaneously in multiple tabs.

I'll close this PR now...
MV

**Comment by jpmv27** [comment]
OK< I see the problem now. Not sure it justifies these changes, I will open an issue and we can discuss there

**Comment by jpmv27** [comment]
New commit solves #345 by leveraging tab-scope variable introduced to fix #344

**Comment by majutsushi** [comment]
Thanks for the explanations, and for all your work! I've confirmed the issue you described in #344 and that the pull request fixes it. I guess #344 can be closed as well then?

**Comment by jpmv27** [comment]
Yes, thanks.
MV

**Pull request merged**
