### PR TITLE
possible bug adding a new filename to _files dictionary

### PR DESCRIPTION
**Pull request by cridemichel**
If I understood correctly the logic, this bug is rather critical since fileinfo is used as dictionary index intead of the filename. Anyway I can not prove it is related to #558.

### CODE REVIEW

**Comment by alerque** [comment]
Again, thanks for the contribution. I squashed this because you submitted it with a previous commit already merged, if you work off an updated master there will be a cleaner history for reviewing PRs ;-)

**Comment by cridemichel** [comment]
> Again, thanks for the contribution. I squashed this because you submitted it with a previous commit already merged, if you work off an updated master there will be a cleaner history for reviewing PRs ;-)

ok I apologize for the inconvenient, next time I will work of an updated master...

**Comment by cridemichel** [comment]
I think we have to revert both commits since a:0 counts the number of variable arguments and *not* the total number of arguments hence previous code both in AutoUpdate and put functions was ok....

**Comment by alerque** [comment]
Oops. Are you sure? I actually looked up the docs on that myself before merging the first PR. I could have read it wrong as well...

**Comment by cridemichel** [comment]
I did some experiments writing some log messages,
but double check before reverting commits…

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by alerque** [comment]
@cridemichel Reverted both.

**Comment by cridemichel** [comment]
ok

Cristiano De Michele
cristiano.demichele@gmail.com

**Pull request merged**
