### PR TITLE
Verify that window number is valid before switching to it

### LINKED ISSUE #305: Error when quit file while tagbar open
I got the following error when I try to close file while tagbar is still open:

screen shot 2016-02-04 at 7 46 38 pm

I am using tagbar with macvim.

### PR DESCRIPTION
**Pull request by joegrasse**
Fixes #305

### CODE REVIEW

**Comment by codinfox** [comment]
@joegrasse Unfortunately this leads to error on macvim:

```
Error detected while processing /Users/Codinfox/.vim/bundle/tagbar/plugin/tagbar.vim:
line    1:
E169: Command too recursive
Tagbar: Could not load plugin code, check your runtimepath!
```

**Comment by joegrasse** [comment]
Interesting. Not sure what would cause the recursive loop to happen. Is there any other differences between your tagbar.vim and the one in the pull request?

**Comment by codinfox** [comment]
I directly used your pull request. :(

**Comment by dperny** [comment]
This PR fixes a bug related to NERDTree. If NERDTree is opened, the main text editing split switched to, Tagbar is opened, and then the main editing split is closed without switching between any splits, an error is thrown.

**Comment by majutsushi** [comment]
Thanks! I've merged your pull request after a small change due to a conflict.

**Pull request closed without merging**
