### PR TITLE
new option: g:tagbar_python_system to allow invoke ctags from python in windows

### PR DESCRIPTION
**Pull request by skywind3000**
new option: `g:tagbar_python_system` in windows, default is 0, set to non-zero to use python to invoke `ctags` instead of using default vim `system` function. 

Vim's `system` in windows will pop up a annoying window icon in taskbar, which seems like some virus when using tagbar open a new file on windows gvim (almost three cmd.exe window icon popped up in taskbar when I open a new file). 

Vim's default `system` in windows is very annoying. so I provide this option to allow windows user running tagbar in a neat way if they set it to non-zero and has('python'). 

Pop-up windows will be killed in windows if this option has been set to non-zero.

### CODE REVIEW

**Comment by skywind3000** [comment]
tagbar_flicker_windows

Please see the gif screen capture above, calling vim's `system()` on windows is very annoying, popup-windows continue flicker under taskbar, just like a virus ..

**Comment by majutsushi** [comment]
Thanks, that's a clever idea! I just have a few comments:

- Would there be any downsides to always using the Python method if it is available? I think it would be great if users didn't have to explicitly set a variable to get the benefits of this.
- The functionality should be able to support both Python 2 and 3, depending on what is available.
- The Python variable names could be a bit more verbose :)

**Comment by skywind3000** [comment]
There has downside to choose python by default if python is available:
Even if has('python') returns 1 on windows, it doesn't mean we can truely use python.
vim on windows can only cooperate with python 2.7.0 - 2.7.9, something wrong in both windows vim and python. 
that means if user has python 2.7.10 vim will returns python available, but it will continue prompt python import error if we invoke any python statement.
So I think it is better to leave this option to people who really know how to config python correctly under windows.

How about this ?
g:tagbar_python_system = 0   -> default vim's system
g:tagbar_python_system = 1   -> python2
g:tagbar_python_system = 2   -> python3

If it is ok, I will reopen a new PR and modify the variable names to something not so verbose ?
Or if you think you can handle it better (better coding style and intergration), let's close this PR and wait for your new version ?

All I want is to get rid of the task bar flicker each time when I open tagbar.

**Comment by skywind3000** [comment]
Python version issue has been discussing here:
https://groups.google.com/forum/#!searchin/vim_dev/python|sort:relevance/vim_dev/fDpkOPpWw_0/KFXcEJZMHAAJ

It is a little tricky to get python work with gvim on windows.
tagbar may fail with any python misconfiguration.

So it is better to have an option to the people who truely understand it.

**Comment by majutsushi** [comment]
Okay, I've looked into this a bit more and realized that it is going to take a bit more work to do properly. I don't want to have to set the `shell` argument in Python since that's a potential security risk, so I'm going to have to restructure things a bit to do the escaping differently for Vim's `system()` and Python. So I'm keen to get this to work, but it's going to take a bit longer.

**Comment by skywind3000** [comment]
thanks

**Comment by skywind3000** [comment]
Currently, I have to modify the code in tagbar myself to solve the flicker, 
but I don't want to do it any more.
Rewrote the python system routine, better variable names supports py2 + py3,
I don't know whether it could be helpful: 

```VimL
" call python system to avoid window flicker on windows
function! s:python_system(command)
	let mswin = has('win32') || has('win16') || has('win95') || has('win64')
	if mswin != 0 && has('python')
		py import subprocess, vim
		py argv = {'args': vim.eval('a:command'), 'shell': True}
		py argv['stdout'] = subprocess.PIPE
		py argv['stderr'] = subprocess.STDOUT
		py p = subprocess.Popen(**argv)
		py text = p.stdout.read()
		py p.stdout.close()
		py p.wait()
		if has('patch-7.4.145') || v:version >= 800
			let l:text = pyeval('text')
		else
			py text = text.replace('\\', '\\\\').replace('"', '\\"')
			py text = text.replace('\n', '\\n').replace('\r', '\\r')
			py vim.command('let l:text = "%s"'%text)
		endif
		return l:text
	elseif mswin != 0 && has('python3')
		py3 import subprocess, vim
		py3 argv = {'args': vim.eval('a:command'), 'shell': True}
		py3 argv['stdout'] = subprocess.PIPE
		py3 argv['stderr'] = subprocess.STDOUT
		py3 p = subprocess.Popen(**argv)
		py3 text = p.stdout.read()
		py3 p.stdout.close()
		py3 p.wait()
		if has('patch-7.4.145') || v:version >= 800
			let l:text = py3eval('text')
		else
			py3 text = text.replace('\\', '\\\\').replace('"', '\\"')
			py3 text = text.replace('\n', '\\n').replace('\r', '\\r')
			py3 vim.command('let l:text = "%s"'%text)
		endif
		return l:text
	else
		return system(a:command)
	endif
endfunc
```

**Comment by tuyenpm9** [comment]
@skywind3000 : I put the function in vimrc but I still have at least one flick. Gvim 1-1284 on windows 10, +python3/dyn, `echo has('python3')` give 1.

**Comment by skywind3000** [comment]
You should modify tagbar source, not only your vimrc.

**Comment by tuyenpm9** [comment]
@skywind3000 : I changed tagbar.vim follow the changes in your commit but flick still happen. Do you encounter the same?

**Comment by skywind3000** [comment]
add: 

    let g:tagbar_python_system = 1 

in your vimrc to enable this.

**Comment by tuyenpm9** [comment]
@skywind3000 : Sorry but it didn't work, still flicking. What about this function? What it used for?  
```
" call python system to avoid window flicker on windows
function! s:python_system(command)
    let mswin = has('win32') || has('win16') || has('win95') || has('win64')
    if mswin != 0 && has('python')
        py import subprocess, vim
        py argv = {'args': vim.eval('a:command'), 'shell': True}
        py argv['stdout'] = subprocess.PIPE
        py argv['stderr'] = subprocess.STDOUT
        py p = subprocess.Popen(**argv)
        py text = p.stdout.read()
        py p.stdout.close()
        py p.wait()
        if has('patch-7.4.145') || v:version >= 800
            let l:text = pyeval('text')
        else
            py text = text.replace('\\', '\\\\').replace('"', '\\"')
            py text = text.replace('\n', '\\n').replace('\r', '\\r')
            py vim.command('let l:text = "%s"'%text)
        endif
        return l:text
    elseif mswin != 0 && has('python3')
        py3 import subprocess, vim
        py3 argv = {'args': vim.eval('a:command'), 'shell': True}
        py3 argv['stdout'] = subprocess.PIPE
        py3 argv['stderr'] = subprocess.STDOUT
        py3 p = subprocess.Popen(**argv)
        py3 text = p.stdout.read()
        py3 p.stdout.close()
        py3 p.wait()
        if has('patch-7.4.145') || v:version >= 800
            let l:text = py3eval('text')
        else
            py3 text = text.replace('\\', '\\\\').replace('"', '\\"')
            py3 text = text.replace('\n', '\\n').replace('\r', '\\r')
            py3 vim.command('let l:text = "%s"'%text)
        endif
        return l:text
    else
        return system(a:command)
    endif
endfunc
```

**Comment by skywind3000** [comment]
check my version:

https://github.com/skywind3000/vim/blob/master/autoload/tagbar.vim
https://github.com/skywind3000/vim/blob/master/plugin/tagbar.vim

**Comment by tuyenpm9** [comment]
I replaced two your files with mine (python3) but errors occur:
```
Error detected while processing 
C:\Users\YYYYY\vimfiles\pack\plugins\s
tart\tagbar\plugin\tagbar.vim:

line    7:

E477: No ! allowed: <!DOCTYPE 
html>

line    8:

E488: Trailing characters: <html 
lang=

line    9:

E488: Trailing characters:   <head>

line   10:

E488: Trailing characters:     <meta 
charset=

line   11:

E488: Trailing characters:   <link rel=

line   12:

E488: Trailing characters:   <link rel=

line   13:

E488: Trailing characters:   <link rel=

line   14:

E488: Trailing characters:   <link rel=

line   15:

E488: Trailing characters:   <link rel=

line   16:

E488: Trailing characters:   <link rel=

line   17:

E488: Trailing characters:   <link rel=

line   21:

E488: Trailing characters:   <link 
crossorigin=

line   22:

E488: Trailing characters:   <link 
crossorigin=

line   28:

E488: Trailing characters:   <meta 
name=

line   30:

E488: Trailing characters:   <title>vim
/tagbar.vim at master · skywind3000/
vim</title>

line   31:

E488: Trailing characters:   <link rel=

line   32:

E488: Trailing characters:   <link rel=

line   33:

E488: Trailing characters:   <meta 
property=

line   36:

E488: Trailing characters:     <meta 
content=

line   38:

E488: Trailing characters:   <link rel=

line   39:

E488: Trailing characters:   <link rel=

line   40:

E488: Trailing characters:   <meta 
name=

line   41:

E488: Trailing characters:   <link rel=

line   42:

E488: Trailing characters:   <meta 
name=

line   45:

E488: Trailing characters:   <meta 
name=

line   47:

E488: Trailing characters:   <meta 
name=

line   48:

E488: Trailing characters: <meta 
name=

line   49:

E488: Trailing characters: <meta 
name=

line   50:

E488: Trailing characters:     <meta 
name=

line   52:

E488: Trailing characters: <meta 
content=

line   53:

E488: Trailing characters: <meta 
content=

line   58:

E488: Trailing characters:   <meta 
class=

line   63:

E488: Trailing characters:       <meta 
name=

line   64:

E488: Trailing characters:   <meta 
name=

line   66:

E488: Trailing characters:       <meta 
name=

line   67:

E488: Trailing characters:     <meta 
name=

line   69:

E488: Trailing characters:     <meta 
name=

line   71:

E488: Trailing characters:   <meta 
name=

line   73:

E488: Trailing characters:   <meta 
http-equiv=

line   76:

E488: Trailing characters:       <link 
href=

line   78:

E488: Trailing characters:   <meta 
name=

line   79:

E488: Trailing characters:   <meta 
name=

line   81:

E488: Trailing characters:   <meta 
content=

line   84:

E488: Trailing characters:     <link 
rel=

line   87:

E488: Trailing characters:   <meta 
name=

line   89:

E488: Trailing characters:   <meta 
name=

line   91:

E488: Trailing characters:   <link rel=

line   92:

E488: Trailing characters:   <link rel=

line   94:

E488: Trailing characters: <meta 
name=

line   98:

E488: Trailing characters:   </head>

line  100:

E488: Trailing characters:   <body 
class=

line  103:

E488: Trailing characters:   <div 
class=

line  104:

E488: Trailing characters:     <a href=

line  105:

E488: Trailing characters:     <div id=

line  114:

E488: Trailing characters: <header 
class=

line  115:

E488: Trailing characters:   <div 
class=

line  116:

E488: Trailing characters:     <div 
class=

line  117:

E488: Trailing characters:       <a 
class=

line  118:

E488: Trailing characters:   <svg 
aria-hidden=

line  119:

E488: Trailing characters: </a>

line  122:

E488: Trailing characters:     </div>

line  124:

E488: Trailing characters:     <div 
class=

line  125:

E488: Trailing characters:       <div 
class=

line  126:

E488: Trailing characters:             
<div class=

line  127:

E488: Trailing characters:               
<div class=

line  128:

E477: No ! allowed:   <!-- '"` --><!-- 
</textarea></xmp> --></option></
form><form accept-charset="UTF-8"
```  
Any suggestions?

**Comment by skywind3000** [comment]
https://github.com/skywind3000/vim/raw/master/autoload/tagbar.vim
https://github.com/skywind3000/vim/raw/master/plugin/tagbar.vim

**Comment by tuyenpm9** [comment]
@skywind3000 : Thanks, select, copy and paste text in your links. No errors but flick still happen, maybe it doesn't work with python3 or vim8?  
`let g:tagbar_python_system = 1` is in vimrc.

**Comment by skywind3000** [comment]
It only works with python2

**Comment by tuyenpm9** [comment]
@skywind3000 : Vim that has `+python/dyn` can be considered has python2 feature? but `:echo has('python')` result `0`.

**Comment by skywind3000** [comment]
It is out of the topic, you should google python2 + vim setup

**Comment by wsdjeg** [comment]
@skywind3000 you can hide the cmd windows when using `systme()` in windows.

**Comment by skywind3000** [comment]
@wsdjeg that only works on neovim

**Comment by wsdjeg** [comment]
I need to say has("python") is not enough to check if gvim support :py command. sometimes even if it return 1, user still can not use :py command.

**Comment by tuyenpm9** [comment]
It would be great if we can patch this using python 3 ver.

**Comment by alerque** [comment]
At this point I don't even care if this works on Python 2 which is past End-Of-Life. If anybody wants to work on making this work on Python 3 I'd be happy to re-review it.

**Comment by alerque** [comment]
@skywind3000 That's looking a lot better than the code in this PR right now! Can you amend the commit in your branch to update this PR with that code? It might need a little tweaking but that looks like something we can work with!

**Comment by skywind3000** [comment]
@alerque , done !

https://github.com/majutsushi/tagbar/pull/611

you can try:

```VimL
Plug 'skywind3000/tagbar'
```

directly.

**Pull request closed without merging**
