### PR TITLE
Add support for Fishman Ctags (issue 225)

### PR DESCRIPTION
**Pull request by primitivorm**
resolve issue 225:

    Se ha detectado un error al procesar function tagbar#ToggleWindow..<SNR>164_ToggleWindow..<SNR>164_OpenWindow..<SNR>164_Init..<SNR>164_CheckForExCtags..<SNR>164_CtagsErrMsg:
        línea   10
        Tagbar: Ctags doesn't seem to be Exuberant Ctags!
        GNU ctags will NOT WORK. Please download Exuberant Ctags from ctags.sourceforge.net and install it in a directory in your $PATH or set g:tagbar_ctags_bin.
        Executed command: "ctags --version"
        Command output:
        Fishman Ctags Development, Copyright (C) 1996-2009 Darren Hiebert
          Compiled: Oct 21 2014, 17:07:07
            Addresses: <dhiebert@users.sourceforge.net>, https://github.com/fishman/ctags
              Optional compiled features: +win32, +wildcards, +regex, +internal-sort

### CODE REVIEW

**Comment by Pyrohh** [comment]
Just a heads up, this will probably be unecessary assuming the following is merged https://github.com/fishman/ctags/pull/209

**Comment by majutsushi** [comment]
Thanks, I'll keep an eye on that!

**Comment by Pyrohh** [comment]
The mentioned PR has been merged, and it now seems to work fine in conjunction with tagbar.

**Comment by majutsushi** [comment]
Thanks, I guess I can close this then.

**Pull request closed without merging**
