### PR TITLE
possible bug in AutoUpdate function

### LINKED ISSUE #558: no tags found...but they were previously there
Hi,
this is a description of the odd behavior which I experienced quite frequently
using tagbar:

1) I enable the tagbar for a c++ file (mcsim_boxes.hpp in the logfile attached)
2) all tags of such file are correctly shown in the tagbar
3) I switch to another file in the same buffer (called partcile_lj.hpp in the logfile)
4) I switch back to the file mcsim_boxes.hpp 
5) in the tagbar there are not tags but it says: "no tags found"

this behavior seems to appear after a certain amount
of switches among all files of my project.
A log file, obtained by TabgarDebug command, is attached.

[tagbardebug.log.gz](https://github.com/majutsushi/tagbar/files/3767012/tagbardebug.log.gz)

### PR DESCRIPTION
**Pull request by cridemichel**
this patch should possibly fix #558

### CODE REVIEW

**Comment by alerque** [comment]
Thanks for the contribution @cridemichel! I poked around and it seems pretty clear this is indeed a bug. Whether it fixes the other problem or not remains to be seen.

**Comment by cridemichel** [comment]
good to know, I hope it will fix my issue too :-)

**Comment by cridemichel** [comment]
bug #558 unfortunately is still there...

**Comment by alerque** [comment]
Too bad. I've reopened the issue so we can keep track of it. This was still a good catch...

**Pull request merged**
